import BookCard from './BookCard';
import {
  Container,
  Book,
  ListsContainer,
  AttributeList,
  ValueList,
  BookName,
  Attribute,
  Author,
  Year,
  Pages,
  Icon,
  ButtonResume,
  ResumeSection,
  Stars,
} from './BookCard.styled';
import LibraryView from './LibraryView';
import {
  Library,
  Title,
  AttributeListDesktop,
  List,
  ButtonTraining,
  ButtonName,
  ButtonAdd,
  AttributeBook,
  AttributeAuthor,
  AttributeYear,
  AttributePages,
  AttributeRating,
} from './LibraryView.styled';

export {
  BookCard,
  LibraryView,
  Container,
  Book,
  ListsContainer,
  AttributeList,
  ValueList,
  BookName,
  Attribute,
  Author,
  Year,
  Pages,
  Icon,
  Library,
  Title,
  AttributeListDesktop,
  List,
  ButtonTraining,
  ButtonName,
  ButtonAdd,
  AttributeBook,
  AttributeAuthor,
  AttributeYear,
  AttributePages,
  AttributeRating,
  ButtonResume,
  ResumeSection,
  Stars,
};
